version: '3.9'

services:
  postgres:
    container_name: prakticum-pgdb
    image: postgres:14
    restart: always
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
    networks:
      - awesome

  pgadmin:
    container_name: prakticum-pgadmin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_PORT}
    ports:
      - '${PGADMIN_PORT}:${PGADMIN_PORT}'
    volumes:
      - ./tmp/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - awesome

  client:
    container_name: prakticum-client
    image: prakticum-client
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        CLIENT_PORT: ${CLIENT_PORT}
    restart: always
    ports:
      - '${CLIENT_PORT}:${CLIENT_PORT}'
    environment:
      - CLIENT_PORT=${CLIENT_PORT}
      - SERVER_PORT=${SERVER_PORT}
    depends_on:
      - server
    networks:
      - awesome

  server:
    container_name: prakticum-server
    image: prackicum-server
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        SERVER_PORT: ${SERVER_PORT}
    restart: always
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    environment:
      SERVER_PORT: ${SERVER_PORT}
    depends_on:
      - pgadmin
    networks:
      - awesome

networks:
  awesome:
    driver: bridge
